### ISSUE TITLE
bunch of followers that i can't export 

### ISSUE THREAD

**Issue by imankiyumarsi** [novitae/Tenai#3]
such a good tool!
I have problem with exporting the followers username. i tested with 2 or 3 diffrent account several times but each time it's stop under 10000 usernames and i can't resume the exporting. part for exporting is not work for me.
the error is:
PrivateAccError: --username is a private account that you're not following.
after this function didn't go forward and stop. i followed  the account but it's not working.

**Comment by novitae** [comment]
It seems you're off-topic here ... Tenai is made to show some followers of a private instagram account.
I guess you're talking of [Sterra](https://github.com/novitae/sterraxcyl), open your issue there please :)
